---
- hosts: all
  become: yes
  tasks: 
  - name: Install packages
    apt:
      name:
      - apache2
      - mysql-server
      - libapache2-mod-auth-mysql
      - php-mysql
      - php
      - libapache2-mod-php
      - python3-mysqldb
      state: latest
      cache_valid_time: 3600
